name: hyperlink
version: 0.0.5
description: A Flutter package for rendering text with clickable hyperlinks.
repository: https://github.com/Odinachi/hyperlink

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



